version: '3.8'

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      - JAVA_HOME=/usr/local/openjdk-23
    ports:
      - "8080:8080"
    user: vscode
