services:
  playground-java:
    container_name: playground-java
    hostname: java
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: $USERNAME_
        UID: $UID
        GID: $GID
    restart: always
    working_dir: /workspace
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
    # environment:
    #   - JAVA_HOME=/usr/local/openjdk-23
    # ports:
    #   - "8080:8080"
    # user: vscode
