services:
  playground-java:
    container_name: 'playground-java'
    hostname: 'java'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    environment:
      - USERNAME=${USERNAME}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - JAVA_HOME=${JAVA_HOME}
    restart: always
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /workspace
